config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'home', to: 'pages#home', as: 'new_message'
  post 'home', to: 'pages#create', as: 'create_message'
  # get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# class Message < ApplicationRecord
# end

class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body

  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @message = Message.new
  end

  # def new
  #   @message = Message.new
  # end

  def create

    @message = Message.new message_params
    if @message.valid?
      MessageMailer.contact(@message).deliver_now
      redirect_to new_message_url, notice: "Message sending, thanks!"
    else
      render :home
    end
  end

  private
  def message_params
    params.require(:message).permit(:name, :email, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 footer-copyright">
                © MisterStark.ID - All rights reserved
                <div class="credits">
                    Themes <a href="https://bootstrapmade.com/demo/Bethany/">Bethany Theme</a> | Modified by <a href="http://coffeecodedev.id">Coffee Code Dev</a> | Hosting by <a href="http://misterstark.id">MisterStark.ID</a>
                </div>
            </div>
            <div class="col-sm-5 footer-social">
                <div class="pull-right hidden-xs hidden-sm">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                    <a href="#"><i class="fa fa-github"></i></a>
                    <a href="#"><i class="fa fa-instagram"></i></a>
                    <!-- <a href="#"><i class="fa fa-google-plus"></i></a>
                    <a href="#"><i class="fa fa-pinterest"></i></a> -->
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!--header-->
<header class="main-header" id="header">
    <div class="bg-color">
        <!--nav-->
        <nav class="nav navbar-default navbar-fixed-top">
            <div class="container">
                <div class="col-md-12">
                    <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false" aria-controls="navbar">
                        <span class="fa fa-bars"></span>
                    </button>
                        <a href="#" class="navbar-brand">MisterStark.ID</a>
                    </div>
                    <div class="collapse navbar-collapse navbar-right" id="mynavbar">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#header">Home</a></li>
                            <li><a href="#feature">Feature</a></li>
                            <!-- <li><a href="#portfolio">Portfolio</a></li> -->
                            <li><a href="#contact">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        <!--/ nav-->
        <div class="container text-center">
            <div class="wrapper wow fadeInUp delay-05s" >
                <h2 class="top-title">Hosting & Development</h2>
                <h3 class="title">MisterStark.ID</h3>
                <h4 class="sub-title">We Serve with Amazing Service</h4>
                <!-- <button type="submit" class="btn btn-submit">Download Now</button> -->
            </div>
        </div>
    </div>
</header>
<!--/ header-->

app/views/layouts/_metahead.html.erb
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bethany Bootstrap Theme</title>
<meta name="description" content="MisterStark.ID | Setup and Maintenance Server | Web Hosting">
<meta name="keywords" content="misterstark.id, setup server, maintenance server, setup vps, maintenance vps, setup and maintenance server, setup and maintenance vps, setup and maintenance, server, vps, web hosting, hosting, website developer, developer, development, solo website developer, solo web hosting, surakarta web developer, surakarta web hosting, web hosting murah, jasa web hosting solo, jasa setup maintenance solo">
<link href='https://fonts.googleapis.com/css?family=Lato:400,700,300|Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Jockey+One|Teko" rel="stylesheet">

<script src="//cdnjs.cloudflare.com/ajax/libs/wow/0.1.12/wow.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MisterstarkId</title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/metahead' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<!-- <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p> -->
<section id="cta-1">
    <div class="container">
        <div class="row">
            <div class="cta-info text-center">
                <h3><span class="dec-tec">“</span>Everything is designed. Few things are designed well.<span class="dec-tec">”</span></h3>
            </div>
        </div>
    </div>
</section>

<section id="feature" class="section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-3 wow fadeInLeft delay-05s">
                <div class="section-title">
                    <h2 class="head-title">Features</h2>
                    <hr class="botm-line">
                    <p class="sec-para">Our Feature Installation/Setup, Maintenance, and Consulting.<br>We have Developer more than 5 years professional on field and many portfolio</p>
                </div>
            </div>
            <div class="col-md-9">
                <div class="col-md-6 wow fadeInRight delay-02s">
                    <div class="icon">
                        <i class="fa fa-cogs"></i>
                    </div>
                    <div class="icon-text">
                        <h3 class="txt-tl">Installation/Setup</h3>
                        <p class="txt-para">Our Feature Installation/Setup is installation server with O.S CentOs, Debian, Ubuntu. </p>
                    </div>
                </div>

                <div class="col-md-6 wow fadeInRight delay-02s">
                  <div class="icon">
                      <i class="fa fa-desktop"></i>
                  </div>
                  <div class="icon-text">
                      <h3 class="txt-tl">Maintenance</h3>
                      <p class="txt-para">Our Feature Maintenance usually helping our client to monitoring, backup, and troubleshooting. </p>
                  </div>
                </div>

                <div class="col-md-6 wow fadeInRight delay-04s">
                    <div class="icon">
                        <i class="fa fa-code"></i>
                    </div>
                    <div class="icon-text">
                        <h3 class="txt-tl">Web Development</h3>
                        <p class="txt-para">Our Feature Web Development is helping our client to make website to promotion or make information system. </p>
                    </div>

                </div>
                <div class="col-md-6 wow fadeInRight delay-04s">
                    <div class="icon">
                        <i class="fa fa-lightbulb-o"></i>
                    </div>
                    <div class="icon-text">
                        <h3 class="txt-tl">Consultant</h3>
                        <p class="txt-para">Our Feature Consultant is to helping our client give recommended choice or we helping client to give solutions.  </p>
                    </div>
                </div>
                <div class="col-md-6 wow fadeInRight delay-06s">
                    <div class="icon">
                        <i class="fa fa-mobile"></i>
                    </div>
                    <div class="icon-text">
                        <h3 class="txt-tl">Easy Access</h3>
                        <p class="txt-para">To helping our client we make them to easy access and contact from our system customer service. </p>
                    </div>

                </div>
                <div class="col-md-6 wow fadeInRight delay-06s">
                    <div class="icon">
                        <i class="fa fa-clock-o"></i>
                    </div>
                    <div class="icon-text">
                        <h3 class="txt-tl">24/7 Services</h3>
                        <p class="txt-para">Our Team ready 24/7 if our client have problem and need our help. </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section-padding parallax bg-image-2 section wow fadeIn delay-08s" id="cta-2">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="cta-txt">
                    <h3>Subscribe For Updates</h3>
                    <p>Join our 1000+ subscribers and get access to the latest tools, freebies, product announcements and much more!</p>
                </div>
            </div>
            <!-- <div class="col-md-4 text-center">
                <a href="#" class="btn btn-submit">Subscribe Now</a>
            </div> -->
        </div>
    </div>
</section>

<!-- <section class="section-padding wow fadeInUp delay-02s" id="portfolio">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-sm-12">
                <div class="section-title">
                    <h2 class="head-title">Portfolio</h2>
                    <hr class="botm-line">
                    <p class="sec-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..</p>
                </div>
            </div>
            <div class="col-md-9 col-sm-12">
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port01.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port02.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port03.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port04.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port05.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 padding-right-zero">
                    <div class="portfolio-box design">
                        <img src="assets/port06.jpg" alt="" class="img-responsive">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> -->

<section class="section-padding wow fadeInUp delay-05s" id="contact">
    <div class="container">
        <div class="row white">
            <div class="col-md-8 col-sm-12">
                <div class="section-title">
                    <h2 class="head-title black">Contact Us</h2>
                    <hr class="botm-line">
                    <p class="sec-para black">If you have any question about our service, you can contact us from this form or contact our email..</p>
                    <!-- <p class="sec-para black">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..</p> -->
                </div>
            </div>
            <div class="col-md-12 col-sm-12">
                <div class="col-md-4 col-sm-6" style="padding-left:0px;">
                    <h3 class="cont-title">Email Us</h3>
                    <div id="sendmessage">Your message has been sent. Thank you!</div>
                    <div id="errormessage"></div>
                    <div class="contact-info">
                        <%= form_for @message, class: "contactForm", url: create_message_url do |f| %>
                          <%= notice %>
                          <%= @message.errors.full_messages.join(', ') %>

                          <div class="form-group">
                            <%= f.text_field :name, placeholder: 'Your Name', class: "form-control", data: {rule: "minlen:4", msg: "Please enter at least 4 chars"} %>
                            <div class="validation"></div>
                          </div>
                          <div class="form-group">
                            <%= f.email_field :email, placeholder: 'email', class: "form-control", data:{rule: "email", msg:"Please enter a valid email"} %>
                            <div class="validation"></div>
                          </div>

                          <div class="form-group">
                            <%= f.text_area :body, placeholder: 'Your Message', class: "form-control", rows: "5", data: {rule: "required", msg: "Please write something for us"} %>
                            <div class="validation"></div>
                          </div>
                            <%= f.submit 'Send', class: "btn btn-send" %>
                        <% end %>
                        <!--

                            <button type="submit" class="btn btn-send">Send</button>
                        </form> -->
                    </div>

                </div>
                <div class="col-md-4 col-sm-6">
                    <h3 class="cont-title">Visit Us</h3>
                    <div class="location-info">
                        <p class="white"><span aria-hidden="true" class="fa fa-map-marker"></span>Surakarta, Central Java, Indonesia</p>
                        <!-- <p class="white"><span aria-hidden="true" class="fa fa-phone"></span>Phone: 0039 333 12 68 347</p> -->
                        <p class="white"><span aria-hidden="true" class="fa fa-envelope"></span>Email: <a href="" class="link-dec">cs@misterstark.id</a></p>
                        <!-- <p class="white"><span aria-hidden="true" class="fa fa-map-marker"></span>Via Principe Amedeo 9, Torino, Italy</p>
                        <p class="white"><span aria-hidden="true" class="fa fa-phone"></span>Phone: 0039 333 12 68 347</p>
                        <p class="white"><span aria-hidden="true" class="fa fa-envelope"></span>Email: <a href="" class="link-dec">hi@yourdomain.com</a></p> -->
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="contact-icon-container hidden-md hidden-sm hidden-xs">
                        <span aria-hidden="true" class="fa fa-envelope-o"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>